### ISSUE TITLE
Crash on work profile by (shelter, island)

### ISSUE THREAD

**Issue by esabook** [crdroidandroid/android_frameworks_base#1159]
SystemUI always crash when play audio from youtube app or youtube music, at work profile.

Reproduce:
- Create work profile from shelter, island
- Install youtube app
- Play selected media from feed

Root cause at 
[InfoMediaManager#270](https://github.com/crdroidandroid/android_frameworks_base/blob/4fca639e0d80a1e451dc52ec63b6214ce43c9cec/packages/SettingsLib/src/com/android/settingslib/media/InfoMediaManager.java#L270)

```FATAL EXCEPTION: SysUiBg
Process: com.android.systemui, PID: 18491
java.lang.IndexOutOfBoundsException: Index: -1
	at java.util.Collections$EmptyList.get(Collections.java:4888)
	at com.android.settingslib.media.InfoMediaManager.getActiveRoutingSession(InfoMediaManager.java:270)
	at com.android.settingslib.media.InfoMediaManager.getAvailableRoutes(InfoMediaManager.java:452)
	at com.android.settingslib.media.InfoMediaManager.buildAvailableRoutes(InfoMediaManager.java:442)
	at com.android.settingslib.media.InfoMediaManager.rebuildDeviceList(InfoMediaManager.java:216)
	at com.android.settingslib.media.InfoMediaManager.refreshDevices(InfoMediaManager.java:435)
	at com.android.settingslib.media.InfoMediaManager.startScan(InfoMediaManager.java:146)
	at com.android.settingslib.media.LocalMediaManager.startScan(LocalMediaManager.java:233)
	at com.android.systemui.media.controls.domain.pipeline.MediaDeviceManager$Entry$start$1.run(MediaDeviceManager.kt:188)
	at android.os.Handler.handleCallback(Handler.java:959)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.os.HandlerThread.run(HandlerThread.java:85)```

**Comment by gwolf2u** [comment]
use issue_tracker
