### ISSUE TITLE
Bootloop after encryption with a PIN code

### ISSUE THREAD

**Issue by iusmac** [crdroidandroid/android_frameworks_base#799]
**To Reproduce:**
1. Format /data
2. Make a clean install
3. Set up PIN code for lockscreen
4. Encrypt device

**Expected behavior:**
The device should reboot and ask for the PIN code.

**What I got:**
A bootloop.

Since I keep all my builds, I can confirm that everything works fine on builds before March 9, 2022. All subsequent builds behave the same. According to the crash dump, I'm pretty sure the bug was introduced after:
https://github.com/crdroidandroid/android_frameworks_base/commit/8c08ac30be7b6c7ae0de545bc82ba81cada0d5a2

P.S PINless encryption works fine.

<details>
  <summary>Crash dump</summary>

```php
03-14 09:51:01.117  2324  2376 I RuntimePermissions: observing UserPackageInfoLiveData for 0 in RuntimePermissionsUpgradeController
03-14 09:51:01.165  2318  2318 W AppComponentFactory: No injector for class: class com.crdroid.android.systemui.keyguard.CrDroidKeyguardSliceProvider
03-14 09:51:01.165  2318  2318 W AppComponentFactory: java.lang.NoSuchMethodException: com.android.systemui.dagger.DaggerGlobalRootComponent$SysUIComponentImpl.inject [class com.crdroid.android.systemui.keyguard.CrDroidKeyguardSliceProvider]
03-14 09:51:01.165  2318  2318 W AppComponentFactory: 	at java.lang.Class.getMethod(Class.java:2103)
03-14 09:51:01.165  2318  2318 W AppComponentFactory: 	at java.lang.Class.getMethod(Class.java:1724)
03-14 09:51:01.165  2318  2318 W AppComponentFactory: 	at com.android.systemui.SystemUIAppComponentFactory.lambda$instantiateProviderCompat$1(SystemUIAppComponentFactory.java:93)
03-14 09:51:01.165  2318  2318 W AppComponentFactory: 	at com.android.systemui.SystemUIAppComponentFactory.$r8$lambda$qcrPqG7eXiVK_IrWSM3yDqdi2js(Unknown Source:0)
03-14 09:51:01.165  2318  2318 W AppComponentFactory: 	at com.android.systemui.SystemUIAppComponentFactory$$ExternalSyntheticLambda0.onContextAvailable(Unknown Source:2)
03-14 09:51:01.165  2318  2318 W AppComponentFactory: 	at com.android.systemui.keyguard.KeyguardSliceProvider.onCreateSliceProvider(KeyguardSliceProvider.java:307)
03-14 09:51:01.165  2318  2318 W AppComponentFactory: 	at com.crdroid.android.systemui.keyguard.CrDroidKeyguardSliceProvider.onCreateSliceProvider(CrDroidKeyguardSliceProvider.java:59)
03-14 09:51:01.165  2318  2318 W AppComponentFactory: 	at androidx.slice.SliceProvider.onCreate(SliceProvider.java:211)
03-14 09:51:01.165  2318  2318 W AppComponentFactory: 	at android.content.ContentProvider.attachInfo(ContentProvider.java:2404)
03-14 09:51:01.165  2318  2318 W AppComponentFactory: 	at android.content.ContentProvider.attachInfo(ContentProvider.java:2374)
03-14 09:51:01.165  2318  2318 W AppComponentFactory: 	at androidx.slice.SliceProvider.attachInfo(SliceProvider.java:250)
03-14 09:51:01.165  2318  2318 W AppComponentFactory: 	at androidx.slice.compat.SliceProviderWrapperContainer$SliceProviderWrapper.attachInfo(SliceProviderWrapperContainer.java:74)
03-14 09:51:01.165  2318  2318 W AppComponentFactory: 	at android.app.ActivityThread.installProvider(ActivityThread.java:7422)
03-14 09:51:01.165  2318  2318 W AppComponentFactory: 	at android.app.ActivityThread.installContentProviders(ActivityThread.java:6939)
03-14 09:51:01.165  2318  2318 W AppComponentFactory: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6710)
03-14 09:51:01.165  2318  2318 W AppComponentFactory: 	at android.app.ActivityThread.access$1500(ActivityThread.java:247)
03-14 09:51:01.165  2318  2318 W AppComponentFactory: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2053)
03-14 09:51:01.165  2318  2318 W AppComponentFactory: 	at android.os.Handler.dispatchMessage(Handler.java:106)
03-14 09:51:01.165  2318  2318 W AppComponentFactory: 	at android.os.Looper.loopOnce(Looper.java:201)
03-14 09:51:01.165  2318  2318 W AppComponentFactory: 	at android.os.Looper.loop(Looper.java:288)
03-14 09:51:01.165  2318  2318 W AppComponentFactory: 	at android.app.ActivityThread.main(ActivityThread.java:7839)
03-14 09:51:01.165  2318  2318 W AppComponentFactory: 	at java.lang.reflect.Method.invoke(Native Method)
03-14 09:51:01.165  2318  2318 W AppComponentFactory: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
03-14 09:51:01.165  2318  2318 W AppComponentFactory: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
03-14 09:51:01.169  2318  2318 D AndroidRuntime: Shutting down VM
03-14 09:51:01.169  2318  2318 E AndroidRuntime: FATAL EXCEPTION: main
03-14 09:51:01.169  2318  2318 E AndroidRuntime: Process: com.android.systemui, PID: 2318
03-14 09:51:01.169  2318  2318 E AndroidRuntime: java.lang.RuntimeException: Unable to get provider com.crdroid.android.systemui.keyguard.CrDroidKeyguardSliceProvider: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.android.systemui.statusbar.NotificationMediaManager.addCallback(com.android.systemui.statusbar.NotificationMediaManager$MediaListener)' on a null object reference
03-14 09:51:01.169  2318  2318 E AndroidRuntime: 	at android.app.ActivityThread.installProvider(ActivityThread.java:7427)
03-14 09:51:01.169  2318  2318 E AndroidRuntime: 	at android.app.ActivityThread.installContentProviders(ActivityThread.java:6939)
03-14 09:51:01.169  2318  2318 E AndroidRuntime: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6710)
03-14 09:51:01.169  2318  2318 E AndroidRuntime: 	at android.app.ActivityThread.access$1500(ActivityThread.java:247)
03-14 09:51:01.169  2318  2318 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2053)
03-14 09:51:01.169  2318  2318 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
03-14 09:51:01.169  2318  2318 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:201)
03-14 09:51:01.169  2318  2318 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:288)
03-14 09:51:01.169  2318  2318 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7839)
03-14 09:51:01.169  2318  2318 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
03-14 09:51:01.169  2318  2318 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
03-14 09:51:01.169  2318  2318 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
03-14 09:51:01.169  2318  2318 E AndroidRuntime: Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.android.systemui.statusbar.NotificationMediaManager.addCallback(com.android.systemui.statusbar.NotificationMediaManager$MediaListener)' on a null object reference
03-14 09:51:01.169  2318  2318 E AndroidRuntime: 	at com.android.systemui.keyguard.KeyguardSliceProvider.onCreateSliceProvider(KeyguardSliceProvider.java:319)
03-14 09:51:01.169  2318  2318 E AndroidRuntime: 	at com.crdroid.android.systemui.keyguard.CrDroidKeyguardSliceProvider.onCreateSliceProvider(CrDroidKeyguardSliceProvider.java:59)
03-14 09:51:01.169  2318  2318 E AndroidRuntime: 	at androidx.slice.SliceProvider.onCreate(SliceProvider.java:211)
03-14 09:51:01.169  2318  2318 E AndroidRuntime: 	at android.content.ContentProvider.attachInfo(ContentProvider.java:2404)
03-14 09:51:01.169  2318  2318 E AndroidRuntime: 	at android.content.ContentProvider.attachInfo(ContentProvider.java:2374)
03-14 09:51:01.169  2318  2318 E AndroidRuntime: 	at androidx.slice.SliceProvider.attachInfo(SliceProvider.java:250)
03-14 09:51:01.169  2318  2318 E AndroidRuntime: 	at androidx.slice.compat.SliceProviderWrapperContainer$SliceProviderWrapper.attachInfo(SliceProviderWrapperContainer.java:74)
03-14 09:51:01.169  2318  2318 E AndroidRuntime: 	at android.app.ActivityThread.installProvider(ActivityThread.java:7422)
03-14 09:51:01.169  2318  2318 E AndroidRuntime: 	... 11 more
03-14 09:51:01.171  2014  2190 I am_crash: [2318,0,com.android.systemui,550026765,java.lang.NullPointerException,Attempt to invoke virtual method 'void com.android.systemui.statusbar.NotificationMediaManager.addCallback(com.android.systemui.statusbar.NotificationMediaManager$MediaListener)' on a null object reference,KeyguardSliceProvider.java,319]
03-14 09:51:01.176  2014  2234 D MediaCodecList: codecHandlesFormat: no format, so no extra checks
03-14 09:51:01.176  2014  2234 D MediaCodecList: codecHandlesFormat: no format, so no extra checks
03-14 09:51:01.185  2014  2233 D MediaCodecList: codecHandlesFormat: no format, so no extra checks
03-14 09:51:01.185  2014  2101 I boot_progress_enable_screen: 58510
03-14 09:51:01.186  2014  2233 D MediaCodecList: codecHandlesFormat: no format, so no extra checks
03-14 09:51:01.188  2014  2110 E AndroidRuntime: *** FATAL EXCEPTION IN SYSTEM PROCESS: android.bg
03-14 09:51:01.188  2014  2110 E AndroidRuntime: java.lang.IllegalStateException: Call to getModuleInfo before metadata loaded
03-14 09:51:01.188  2014  2110 E AndroidRuntime: 	at com.android.server.pm.ModuleInfoProvider.getModuleInfo(ModuleInfoProvider.java:205)
03-14 09:51:01.188  2014  2110 E AndroidRuntime: 	at com.android.server.pm.PackageManagerService.getModuleInfo(PackageManagerService.java:9880)
03-14 09:51:01.188  2014  2110 E AndroidRuntime: 	at android.app.ApplicationPackageManager.getModuleInfo(ApplicationPackageManager.java:1113)
03-14 09:51:01.188  2014  2110 E AndroidRuntime: 	at com.android.server.RescueParty$RescuePartyObserver.mayObservePackage(RescueParty.java:657)
03-14 09:51:01.188  2014  2110 E AndroidRuntime: 	at com.android.server.PackageWatchdog$ObserverInternal.onPackageFailureLocked(PackageWatchdog.java:1239)
03-14 09:51:01.188  2014  2110 E AndroidRuntime: 	at com.android.server.PackageWatchdog.lambda$onPackageFailure$4$PackageWatchdog(PackageWatchdog.java:419)
03-14 09:51:01.188  2014  2110 E AndroidRuntime: 	at com.android.server.PackageWatchdog$$ExternalSyntheticLambda9.run(Unknown Source:6)
03-14 09:51:01.188  2014  2110 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:938)
03-14 09:51:01.188  2014  2110 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
03-14 09:51:01.188  2014  2110 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:201)
03-14 09:51:01.188  2014  2110 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:288)
03-14 09:51:01.188  2014  2110 E AndroidRuntime: 	at android.os.HandlerThread.run(HandlerThread.java:67)
03-14 09:51:01.188  2014  2110 I am_crash: [2014,0,system_server,-1,java.lang.IllegalStateException,Call to getModuleInfo before metadata loaded,ModuleInfoProvider.java,205]
03-14 09:51:01.189  2014  2190 I sysui_multi_action: [757,316,758,4,759,-1]
03-14 09:51:01.189  2014  2382 I DropBoxManagerService: add tag=system_app_crash isTagEnabled=true flags=0x2
03-14 09:51:01.189  2318  2318 I Process : Sending signal. PID: 2318 SIG: 9
03-14 09:51:01.190  2014  2110 I DropBoxManagerService: add tag=system_server_crash isTagEnabled=true flags=0x2
03-14 09:51:01.191  2014  2101 I screen_toggled: 1
03-14 09:51:01.192  2014  2101 W KeyguardServiceDelegate: onScreenTurningOn(): no keyguard service!
03-14 09:51:01.195  2014  2383 I OMXClient: IOmx service obtained
03-14 09:51:01.195  1663  2380 I OMXStore: makeComponentInstance(OMX.google.vorbis.decoder) in android.hardwar process
03-14 09:51:01.197  2014  2390 I OMXClient: IOmx service obtained
03-14 09:51:01.197  1663  1731 I OMXStore: makeComponentInstance(OMX.google.vorbis.decoder) in android.hardwar process
03-14 09:51:01.224  2014  2110 I Process : Sending signal. PID: 2014 SIG: 9
03-14 09:51:01.269  1950  1950 I Zygote  : Process 2318 exited due to signal 9 (Killed)
```
</details>

**Comment by koron393** [comment]
Same.
And suddenly this is not fixed at 12.1 branch.
Please revert smart space commits.

**Comment by neobuddy89** [comment]
FBE or FDE?

**Comment by koron393** [comment]
FDE.
I can successfully decrypt until early March.

**Comment by iusmac** [comment]
@neobuddy89 FDE me too

**Comment by neobuddy89** [comment]
Should be fixed with below pushed commit on 12.1
https://github.com/crdroidandroid/android_frameworks_base/commit/1d6cb2e97d21f979598b2de0b48a80ed26e3300e

Test and let us know.

**Comment by koron393** [comment]
I confirm it's fix

**Comment by iusmac** [comment]
@koron393 what's the date of your last full synchronization? Because smart space commit returned yesterday, does your build include it?
